DROP DATABASE IF EXISTS `samplewiki`;
CREATE DATABASE `samplewiki` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;
USE `samplewiki`;

CREATE TABLE `Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `PasswordHash` VARCHAR(200) NOT NULL,
  `Role` INT NOT NULL DEFAULT 1,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  `LastLoginAt` DATETIME NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UX_Users_Username` (`Username`),
  UNIQUE KEY `UX_Users_Email` (`Email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Artists` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  `Description` TEXT NULL,
  `WikiLink` VARCHAR(500) NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Artists_Name` (`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Albums` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `ReleaseYear` INT NULL,
  `ArtistId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Albums_ArtistId_Title` (`ArtistId`,`Title`),
  CONSTRAINT `FK_Albums_Artist` FOREIGN KEY (`ArtistId`) REFERENCES `Artists` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Tracks` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `TrackNumber` INT NULL,
  `Genre` VARCHAR(50) NULL,
  `ResourceUrl` VARCHAR(500) NULL,
  `AlbumId` INT NOT NULL,
  `ArtistId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Tracks_AlbumId_TrackNumber` (`AlbumId`,`TrackNumber`),
  CONSTRAINT `FK_Tracks_Album` FOREIGN KEY (`AlbumId`) REFERENCES `Albums` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_Tracks_Artist` FOREIGN KEY (`ArtistId`) REFERENCES `Artists` (`Id`) ON DELETE RESTRICT,
  CONSTRAINT `FK_Tracks_User` FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Samples` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Type` INT NOT NULL DEFAULT 0 COMMENT '0=Sample, 1=Interpolation, 2=Cover, 3=Remix',
  `StartTimeSeconds` INT NULL COMMENT 'Timecode where the sample starts (in seconds)',
  `TrackId` INT NOT NULL COMMENT 'Track that contains the sample',
  `SampledTrackId` INT NOT NULL COMMENT 'Track being sampled',
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Samples_TrackId` (`TrackId`),
  KEY `IX_Samples_SampledTrackId` (`SampledTrackId`),
  CONSTRAINT `FK_Samples_Track` FOREIGN KEY (`TrackId`) REFERENCES `Tracks` (`Id`) ON DELETE RESTRICT,
  CONSTRAINT `FK_Samples_SampledTrack` FOREIGN KEY (`SampledTrackId`) REFERENCES `Tracks` (`Id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Artworks` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `ImageUrl` TEXT NOT NULL,
  `Description` TEXT NULL,
  `AlbumId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Artworks_AlbumId` (`AlbumId`),
  CONSTRAINT `FK_Artworks_Album` FOREIGN KEY (`AlbumId`) REFERENCES `Albums` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Revisions` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ChangeType` INT NOT NULL,
  `EntityName` VARCHAR(100) NOT NULL,
  `EntityId` INT NOT NULL,
  `Description` TEXT NOT NULL,
  `OldValues` JSON NULL,
  `NewValues` JSON NULL,
  `UserId` INT NOT NULL,
  `TrackId` INT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Revisions_Entity` (`EntityName`,`EntityId`),
  KEY `IX_Revisions_UserId` (`UserId`),
  CONSTRAINT `FK_Revisions_User` FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE RESTRICT,
  CONSTRAINT `FK_Revisions_Track` FOREIGN KEY (`TrackId`) REFERENCES `Tracks` (`Id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SELECT 'Database created successfully' AS Message;
