-- Create database and use it
CREATE DATABASE IF NOT EXISTS `samplewiki` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;
USE `samplewiki`;

-- Users
CREATE TABLE IF NOT EXISTS `Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `PasswordHash` VARCHAR(200) NOT NULL,
  `Role` INT NOT NULL DEFAULT 1,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  `LastLoginAt` DATETIME NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UX_Users_Username` (`Username`),
  UNIQUE KEY `UX_Users_Email` (`Email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Artists
CREATE TABLE IF NOT EXISTS `Artists` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  `Description` TEXT NULL,
  `WikiLink` VARCHAR(500) NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Artists_Name` (`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Albums
CREATE TABLE IF NOT EXISTS `Albums` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `ReleaseYear` INT NULL,
  `Description` TEXT NULL,
  `ArtistId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Albums_ArtistId_Title` (`ArtistId`,`Title`),
  CONSTRAINT `FK_Albums_Artist` FOREIGN KEY (`ArtistId`) REFERENCES `Artists` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tracks
CREATE TABLE IF NOT EXISTS `Tracks` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `DurationSeconds` INT NOT NULL,
  `TrackNumber` INT NULL,
  `Genre` VARCHAR(50) NULL,
  `AlbumId` INT NOT NULL,
  `ArtistId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Tracks_AlbumId_TrackNumber` (`AlbumId`,`TrackNumber`),
  CONSTRAINT `FK_Tracks_Album` FOREIGN KEY (`AlbumId`) REFERENCES `Albums` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_Tracks_Artist` FOREIGN KEY (`ArtistId`) REFERENCES `Artists` (`Id`) ON DELETE RESTRICT,
  CONSTRAINT `FK_Tracks_User` FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Samples
CREATE TABLE IF NOT EXISTS `Samples` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `Type` INT NOT NULL DEFAULT 0,
  `Description` TEXT NULL,
  `Platform` INT NOT NULL DEFAULT 0,
  `PlatformId` VARCHAR(100) NOT NULL,
  `StartTime` VARCHAR(20) NOT NULL,
  `EndTime` VARCHAR(20) NOT NULL,
  `TrackId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Samples_TrackId` (`TrackId`),
  CONSTRAINT `FK_Samples_Track` FOREIGN KEY (`TrackId`) REFERENCES `Tracks` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Artworks
CREATE TABLE IF NOT EXISTS `Artworks` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `ImageUrl` TEXT NOT NULL,
  `Description` TEXT NULL,
  `AlbumId` INT NULL,
  `SampleId` INT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_Artworks_Album` FOREIGN KEY (`AlbumId`) REFERENCES `Albums` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_Artworks_Sample` FOREIGN KEY (`SampleId`) REFERENCES `Samples` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Revisions
CREATE TABLE IF NOT EXISTS `Revisions` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ChangeType` INT NOT NULL,
  `EntityName` VARCHAR(100) NOT NULL,
  `EntityId` INT NOT NULL,
  `Description` TEXT NOT NULL,
  `OldValues` JSON NULL,
  `NewValues` JSON NULL,
  `UserId` INT NOT NULL,
  `TrackId` INT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_Revisions_Entity` (`EntityName`,`EntityId`),
  KEY `IX_Revisions_UserId` (`UserId`),
  CONSTRAINT `FK_Revisions_User` FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE RESTRICT,
  CONSTRAINT `FK_Revisions_Track` FOREIGN KEY (`TrackId`) REFERENCES `Tracks` (`Id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- EF Migrations history (optional)
CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
  `MigrationId` VARCHAR(150) NOT NULL,
  `ProductVersion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`MigrationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
